### ISSUE TITLE
500 Internal Server Error when going to settings

### ISSUE THREAD

**Issue by JohnDoe-dev-spec** [Wizarrrr/wizarr#11]
Hi,

I seem to be getting an Internal Server Error Page, 500 when going to settings. The only thing i changed from when it was working to not working was the removal of the Overseer URL, i left this blank.

Since then it appears to have broken Wizarr.

```
 [2022-09-16 14:22:08 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-09-16 14:22:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
[2022-09-16 14:22:08 +0000] [1] [INFO] Using worker: sync
[2022-09-16 14:22:08 +0000] [7] [INFO] Booting worker with pid: 7
[2022-09-16 14:22:08 +0000] [8] [INFO] Booting worker with pid: 8
[2022-09-16 14:22:08 +0000] [9] [INFO] Booting worker with pid: 9
[2022-09-16 14:22:27,205] ERROR in app: Exception on /settings/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/app/admin.py", line 26, in decorated_function
    return f(*args, **kwargs)
  File "/data/app/admin.py", line 104, in secure_settings
    Settings.key == "overseerr_url").value
AttributeError: 'NoneType' object has no attribute 'value'
[2022-09-16 14:30:22,669] ERROR in app: Exception on /settings/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/app/admin.py", line 26, in decorated_function
    return f(*args, **kwargs)
  File "/data/app/admin.py", line 104, in secure_settings
    Settings.key == "overseerr_url").value
AttributeError: 'NoneType' object has no attribute 'value'
```

Thanks!

**Comment by mtthidoteu** [comment]
> Hi,
> 
> I seem to be getting an Internal Server Error Page, 500 when going to settings. The only thing i changed from when it was working to not working was the removal of the Overseer URL, i left this blank.
> 
> Since then it appears to have broken Wizarr.
> 
> ```
>  [2022-09-16 14:22:08 +0000] [1] [INFO] Starting gunicorn 20.1.0
> [2022-09-16 14:22:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
> [2022-09-16 14:22:08 +0000] [1] [INFO] Using worker: sync
> [2022-09-16 14:22:08 +0000] [7] [INFO] Booting worker with pid: 7
> [2022-09-16 14:22:08 +0000] [8] [INFO] Booting worker with pid: 8
> [2022-09-16 14:22:08 +0000] [9] [INFO] Booting worker with pid: 9
> [2022-09-16 14:22:27,205] ERROR in app: Exception on /settings/ [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/data/app/admin.py", line 26, in decorated_function
>     return f(*args, **kwargs)
>   File "/data/app/admin.py", line 104, in secure_settings
>     Settings.key == "overseerr_url").value
> AttributeError: 'NoneType' object has no attribute 'value'
> [2022-09-16 14:30:22,669] ERROR in app: Exception on /settings/ [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/data/app/admin.py", line 26, in decorated_function
>     return f(*args, **kwargs)
>   File "/data/app/admin.py", line 104, in secure_settings
>     Settings.key == "overseerr_url").value
> AttributeError: 'NoneType' object has no attribute 'value'
> ```
> 
> Thanks!

I see the problem! Should be fixed now!
