### ISSUE TITLE
[HELP] Unable to accept invite - 500 Internal Server Error

### ISSUE THREAD

**Issue by HotshotGT** [Wizarrrr/wizarr#153]
**Describe the bug**
When attempting to accept an invite I receive a "500 Internal Server Error" when the page redirects to "/setup/jellyfin"

**Logs**
```
2023-06-06 02:15:35,015 - ERROR - Exception on /setup/jellyfin [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/jellyfin.py", line 168, in join_jellyfin
    jf_get_users()
  File "/data/app/jellyfin.py", line 181, in jf_get_users
    response = Get("/Users")
               ^^^^^^^^^^^^^
  File "/data/app/jellyfin.py", line 32, in Get
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/usr/local/lib/python3.11/site-packages/requests/utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "/usr/local/lib/python3.11/site-packages/requests/utils.py", line 1056, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: '\t90ccddee4e2d4a8397be33bdd729c8b0'
2023-06-06 02:15:35,017 - ERROR - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Additional context**
The header value specified in the above error is my Jellyfin API key. I've confirmed that the "\t" is not present in the token field of Wizarr's server settings menu, and I can properly scan for libraries without any errors. Running Nginx Proxy Manager, Jellyfin, and Wizarr in docker and have configured the proxy per [this page](https://docs.wizarr.dev/getting-started/reverse-proxy).

**Comment by realashleybailey** [comment]
\t is a representation for a TAB key, instead of copy and pasting the API key try to manually type it in to make sure not other characters accidentally end up in the field.
