### ISSUE TITLE
[HELP] Not sure why not working and joining users.

### ISSUE THREAD

**Issue by rmilyard** [Wizarrrr/wizarr#186]
**Describe the bug**
When I send link to user I invited they walk though setup.  Doesn't seen to create  account on my Plex server.  Also doesn't make overseerr account.

**Screenshots**
![image](https://github.com/Wizarrrr/wizarr/assets/11091710/480a1cc2-5aa9-496e-bbdd-7cb59aaf7b30)

**Logs**
[2023-07-24 17:54:31 -0700] [1] [INFO] Starting gunicorn 20.1.0
[2023-07-24 17:54:31 -0700] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
[2023-07-24 17:54:31 -0700] [1] [INFO] Using worker: sync
[2023-07-24 17:54:31 -0700] [7] [INFO] Booting worker with pid: 7
[2023-07-24 17:54:31 -0700] [8] [INFO] Booting worker with pid: 8
[2023-07-24 17:54:31 -0700] [9] [INFO] Booting worker with pid: 9
WARNING:root:Exception raised while handling cache file './database/sessions/2029240f6d1128be89ddc32729463129'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cachelib/file.py", line 256, in set
    self._run_safely(os.chmod, filename, self._mode)
  File "/usr/local/lib/python3.11/site-packages/cachelib/file.py", line 324, in _run_safely
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
OSError: [Errno 116] Stale file handle: './database/sessions/2029240f6d1128be89ddc32729463129'
Exception in thread Thread-1 (plex_handle_oauth_token):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/data/app/plex.py", line 13, in plex_handle_oauth_token
    email = MyPlexAccount(token).email
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 98, in __init__
    data, initpath = self._signin(username, password, code, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 108, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 195, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (429) too_many_requests; https://plex.tv/users/sign_in.xml 
2023-07-24 19:06:16,636 - ERROR - Too many requests to Plex API
2023-07-24 19:06:36,421 - ERROR - Too many requests to Plex API
[2023-07-25 02:00:01 -0700] [1] [INFO] Handling signal: term
[2023-07-25 02:00:01 -0700] [1] [INFO] Shutting down: Master
[2023-07-25 02:00:25 -0700] [1] [INFO] Starting gunicorn 20.1.0
[2023-07-25 02:00:25 -0700] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
[2023-07-25 02:00:25 -0700] [1] [INFO] Using worker: sync
[2023-07-25 02:00:25 -0700] [7] [INFO] Booting worker with pid: 7
[2023-07-25 02:00:25 -0700] [8] [INFO] Booting worker with pid: 8
[2023-07-25 02:00:25 -0700] [9] [INFO] Booting worker with pid: 9
[2023-07-25 07:39:25 -0700] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
[2023-07-25 07:39:25 -0700] [19] [INFO] Booting worker with pid: 19
Exception in thread Thread-1 (plex_handle_oauth_token):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/data/app/plex.py", line 13, in plex_handle_oauth_token
    email = MyPlexAccount(token).email
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 98, in __init__
    data, initpath = self._signin(username, password, code, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 108, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 195, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (429) too_many_requests; https://plex.tv/users/sign_in.xml 
2023-07-25 07:47:50,285 - ERROR - Too many requests to Plex API
2023-07-25 07:48:08,130 - ERROR - Too many requests to Plex API
2023-07-25 07:51:19,428 - ERROR - Too many requests to Plex API
True
True
True
True
    
```
ERROR:ROOT:SOMETHING BAD 
```

**Additional context**

**Comment by christianmerges** [comment]
It looks like the Plex token is invalid and for trying too often, the api Server blocked u. Try to refresh the token.

**Comment by mgregor7** [comment]
> > Also getting this error. Tried again after regenerating and updating wizarr with new api token. Invite link works on remote end but user is not added to plex server.
> > `[2023-07-31 04:41:07 -0500] [1] [INFO] Starting gunicorn 20.1.0 [2023-07-31 04:41:07 -0500] [1] [INFO] Listening at: http://0.0.0.0:5690 (1) [2023-07-31 04:41:07 -0500] [1] [INFO] Using worker: sync [2023-07-31 04:41:07 -0500] [7] [INFO] Booting worker with pid: 7 [2023-07-31 04:41:07 -0500] [8] [INFO] Booting worker with pid: 8 [2023-07-31 04:41:07 -0500] [9] [INFO] Booting worker with pid: 9 Exception in thread Thread-1 (plex_handle_oauth_token): Traceback (most recent call last): File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner self.run() File "/usr/local/lib/python3.11/threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "/data/app/plex.py", line 13, in plex_handle_oauth_token email = MyPlexAccount(token).email ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 98, in __init__ data, initpath = self._signin(username, password, code, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 108, in _signin data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 195, in query raise BadRequest(message) plexapi.exceptions.BadRequest: (429) too_many_requests; https://plex.tv/users/sign_in.xml `
> 
> Try the `ghcr.io/wizarrrr/wizarr:dev` image

This fixed my error. I had to remove the docker image by stopping and removing the docker, then using docker rmi <id> to delete the cached images. Created the docker again using the dev branch and it fixed my issue. Thanks!
