### ISSUE TITLE
[BUG] Cannot create new user via invite in 2.2.2

### ISSUE THREAD

**Issue by FritzHeiden** [Wizarrrr/wizarr#205]
**Describe the bug**
When using the link for an invite, I am able to enter all the details for the new user, however, clicking on create account leads to a 500 page. I updated from v2.2.1 to v2.2.2 using the Dockerfile. Worked fine before. I use a reverse proxy with nginx.

**Logs**
```
wizarr  | 2023-09-13 14:48:55,133 - ERROR - Unable to get users: no such column: t1.auth
wizarr  | 2023-09-13 14:50:09,501 - ERROR - Exception on /setup/jellyfin [POST]
wizarr  | Traceback (most recent call last):
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3251, in execute_sql
wizarr  |     cursor.execute(sql, params or ())
wizarr  | sqlite3.OperationalError: no such column: t1.auth
wizarr  | 
wizarr  | 
wizarr  | During handling of the above exception, another exception occurred:
wizarr  | 
wizarr  | 
wizarr  | Traceback (most recent call last):
wizarr  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
wizarr  |     response = self.full_dispatch_request()
wizarr  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
wizarr  |     rv = self.handle_user_exception(e)
wizarr  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
wizarr  |     rv = self.dispatch_request()
wizarr  |          ^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
wizarr  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
wizarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/data/app/jellyfin.py", line 201, in join_jellyfin
wizarr  |     jf_get_users()
wizarr  |   File "/data/app/jellyfin.py", line 223, in jf_get_users
wizarr  |     if Users.select():
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2072, in __len__
wizarr  |     self._ensure_execution()
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2054, in _ensure_execution
wizarr  |     self.execute()
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 1971, in inner
wizarr  |     return method(self, database, *args, **kwargs)
wizarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2042, in execute
wizarr  |     return self._execute(database)
wizarr  |            ^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2215, in _execute
wizarr  |     cursor = database.execute(self)
wizarr  |              ^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3259, in execute
wizarr  |     return self.execute_sql(sql, params)
wizarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3249, in execute_sql
wizarr  |     with __exception_wrapper__:
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3019, in __exit__
wizarr  |     reraise(new_type, new_type(exc_value, *exc_args), traceback)
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 192, in reraise
wizarr  |     raise value.with_traceback(tb)
wizarr  |   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3251, in execute_sql
wizarr  |     cursor.execute(sql, params or ())
wizarr  | peewee.OperationalError: no such column: t1.auth
wizarr  | 2023-09-13 14:50:09,507 - ERROR - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by FritzHeiden** [comment]
Works fine if I delete the database and let wizarr create a new one.

**Comment by connwork** [comment]
> Works fine if I delete the database and let wizarr create a new one.

Can you post your nginx config for a guy pulling his hair out?

**Comment by FritzHeiden** [comment]
> Can you post your nginx config for a guy pulling his hair out?


I have nginx running in a docker container. Wizarr and nginx docker containers are in the same virtual network:

```nginx
server {
  listen 80;
  listen [::]:80;
  server_name my.domain.tld;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name my.domain.tld;

  ssl_certificate /etc/letsencrypt/live/my.domain.tld/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/my.domain.tld/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/my.domain.tld/chain.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;

  location / {
    proxy_pass http://wizarr:5690;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    # websockets
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    gzip off;
  }
}

```

**Comment by realashleybailey** [comment]
Looks like it's nothing to do with your Nginx, your database has suffered from a corruption, it's stating auth column is missing.

We no longer support V2 that's why this thread has not been responded to.

If you wish to still use V2 please delete database file and reinstall.

Otherwise we recommend upgrading to V3.
