### ISSUE TITLE
[HELP] Can not get Wizarr to run on my Synology NAS Via docker

### ISSUE THREAD

**Issue by morpheus2n2** [Wizarrrr/wizarr#209]
I have redone this container a number of times over the last 24 hours, I used the docker compose information from the install guide but all I get are these errors in the log and it never boots up.

[2023-09-21 11:46:42 +0000] [8] [INFO] Booting worker with pid: 8

[2023-09-21 11:46:42 +0000] [8] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi

    self.wsgi = self.app.wsgi()

                ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi

    self.callable = self.load()

                    ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

    return self.load_wsgiapp()

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

    return util.import_app(self.app_uri)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app

    mod = importlib.import_module(module)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'run'

[2023-09-21 11:46:42 +0000] [8] [INFO] Worker exiting (pid: 8)

[2023-09-21 11:46:42 +0000] [1] [WARNING] Worker with pid 7 was terminated due to signal 15

[2023-09-21 11:46:42 +0000] [1] [WARNING] Worker with pid 8 was terminated due to signal 15

[2023-09-21 11:46:42 +0000] [1] [INFO] Shutting down: Master

[2023-09-21 11:46:42 +0000] [1] [INFO] Reason: Worker failed to boot.

[2023-09-21 11:48:26 +0000] [1] [INFO] Starting gunicorn 20.1.0

[2023-09-21 11:48:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)

[2023-09-21 11:48:26 +0000] [1] [INFO] Using worker: sync

[2023-09-21 11:48:26 +0000] [6] [INFO] Booting worker with pid: 6

[2023-09-21 11:48:26 +0000] [6] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi

    self.wsgi = self.app.wsgi()

                ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi

    self.callable = self.load()

                    ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

    return self.load_wsgiapp()

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

    return util.import_app(self.app_uri)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app

    mod = importlib.import_module(module)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'run'

[2023-09-21 11:48:26 +0000] [6] [INFO] Worker exiting (pid: 6)

[2023-09-21 11:48:26 +0000] [7] [INFO] Booting worker with pid: 7

[2023-09-21 11:48:26 +0000] [7] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi

    self.wsgi = self.app.wsgi()

                ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi

    self.callable = self.load()

                    ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

    return self.load_wsgiapp()

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

    return util.import_app(self.app_uri)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app

    mod = importlib.import_module(module)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'run'

[2023-09-21 11:48:26 +0000] [7] [INFO] Worker exiting (pid: 7)

[2023-09-21 11:48:26 +0000] [1] [WARNING] Worker with pid 7 was terminated due to signal 15

[2023-09-21 11:48:27 +0000] [1] [INFO] Shutting down: Master

[2023-09-21 11:48:27 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by realashleybailey** [comment]
What Wizarr version are you using, V2 or V3 Beta

**Comment by morpheus2n2** [comment]
V2 I believe its the one thats pulled by docker  via the compose command on the install guide 
```
container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
```

**Comment by realashleybailey** [comment]
Please try using first deleting your Wizarr container, then perform `docker system prune` making sure to delete the Wizarr image and other dangling dependencies, then redownload the image and run the container, if you continue to face issue please do `docker images --digests` and provide the tag and digest sha 256 for the Wizarr image you have on your system

**Comment by morpheus2n2** [comment]
sha256:1345cc56994fa0d4876c2eff3e26c42d47492df77ca1b51ae472fa459b2a0cbe

**Comment by morpheus2n2** [comment]
I have tried 3 more times at fully removing the image alone with any data folders etc and still, the container starts then crashes after a min always with the same errors in the docker log file

**Comment by morpheus2n2** [comment]
any help on this?

**Comment by morpheus2n2** [comment]
I have given up on this, clearly its not going to work and no one seems to want to help oh well

**Comment by realashleybailey** [comment]
> I have given up on this, clearly its not going to work and no one seems to want to help oh well

Github is the worst place for support because notifications often get completely lost, we have an extremely active Discord with lots of members, please come over to there and we can talk through your issue step by step and get it resolved, heres the link https://discord.com/invite/wsSTsHGsqu
