### ISSUE TITLE
3.4.1 error: file not found: /data/package.json

### ISSUE THREAD

**Issue by Bykow** [Wizarrrr/wizarr#226]
Hey,

Just did the update, recreated a new volume for Wizarr, got this error strait away.

```

│ FileNotFoundError: [Errno 2] No such file or directory: '/data/package.json'                                                                                                            │
│ 16:43:56 ERROR Exception on /api/server [GET]                                                                                                                                           │
│ Traceback (most recent call last):                                                                                                                                                      │
│   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request                                                                                      │
│     rv = self.dispatch_request()                                                                                                                                                        │
│          ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                        │
│   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request                                                                                           │
│     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                            │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                            │
│   File "/usr/local/lib/python3.12/site-packages/flask_restx/api.py", line 404, in wrapper                                                                                               │
│     resp = resource(*args, **kwargs)                                                                                                                                                    │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                    │
│   File "/usr/local/lib/python3.12/site-packages/flask/views.py", line 109, in view                                                                                                      │
│     return current_app.ensure_sync(self.dispatch_request)(**kwargs)                                                                                                                     │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                     │
│   File "/usr/local/lib/python3.12/site-packages/flask_restx/resource.py", line 46, in dispatch_request                                                                                  │
│     resp = meth(*args, **kwargs)                                                                                                                                                        │
│            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                        │
│   File "/data/backend/api/routes/server_api.py", line 28, in get                                                                                                                        │
│     "version": str(get_current_version()),                                                                                                                                              │
│                    ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                │
│   File "/data/backend/app/utils/software_lifecycle.py", line 27, in get_current_version                                                                                                 │
│     with open(package, "r", encoding="utf-8") as f:                                                                                                                                     │
│          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                           │
│ FileNotFoundError: [Errno 2] No such file or directory: '/data/package.json'                                                                                                            │
│ 16:43:56 INFO 127.0.0.1 - - [2023-10-07 16:43:56] "GET /api/server HTTP/1.0" 500 448 0.004305                                                                                           │
```

**Comment by Bykow** [comment]
Error on my side..
