### ISSUE TITLE
Error while onboarding a user

### ISSUE THREAD

**Issue by aronjanosch** [Wizarrrr/wizarr#245]
Hi folks,

there error happens after the user created his plex account and was trying to join the server.

Traceback (most recent call last):
  File "/data/backend/helpers/universal.py", line 300, in global_invite_user_to_media_server
    user = universal_invite_user.get(server_type)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/backend/helpers/universal.py", line 288, in <lambda>
    "plex": lambda token, code, **kwargs: invite_plex_user(token=token, code=code),
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/backend/helpers/plex.py", line 132, in invite_plex_user
    invite = invite_method(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/myplex.py", line 327, in inviteFriend
    sectionIds = self._getSectionIds(machineId, sections)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/myplex.py", line 721, in _getSectionIds
    sectionIds.append(allSectionIds[sectionKey])
                      ~~~~~~~~~~~~~^^^^^^^^^^^^

KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/data/backend/helpers/universal.py", line 309, in global_invite_user_to_media_server
    raise BadRequest("There was issue during the account creation") from e
plexapi.exceptions.BadRequest: There was issue during the account creation

**Comment by realashleybailey** [comment]
Goto to Settings->Media Server->Select Libraries and select you Libraries
