### ISSUE TITLE
[Bug] | 410 Gone Response code 410 this endpoint was deprecated and remove

### ISSUE THREAD

**Issue by NOnooSS** [wizarrrr/wizarr#450]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

When the user want to create an account on plex, he has an error on Wizarr
Message is showing something went wrong.
The user is created on Plex and he has access after all but still have an error in the process

### Virtualisation

Docker

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Chrome

### Project Location

Local

### Bug Description

![msedge_LPbLFG5wMp](https://github.com/wizarrrr/wizarr/assets/17955352/50237734-0e48-4f5f-9239-157bb9f530b5)

### Steps to Reproduce

Create an invitation with Wizarrrr
Create an account with plex authentification
Error happen after creation

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/wizarr/backend/helpers/universal.py", line 308, in global_invite_user_to_media_server
    if server_type == "plex": accept_plex_invitation(token=kwargs.get("token"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wizarr/backend/helpers/plex.py", line 166, in accept_plex_invitation
    plex_account.acceptInvite(my_account.email)
  File "/usr/local/lib/python3.12/site-packages/plexapi/myplex.py", line 561, in acceptInvite
    invite = user if isinstance(user, MyPlexInvite) else self.pendingInvite(user, includeSent=False)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/myplex.py", line 689, in pendingInvite
    for invite in self.pendingInvites(includeSent, includeReceived):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/myplex.py", line 709, in pendingInvites
    elem = self.query(MyPlexInvite.REQUESTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/myplex.py", line 248, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (410) gone; https://plex.tv/api/invites/requests <?xml version="1.0" encoding="UTF-8"?> <Response code="410" status="This endpoint was deprecated and removed"/>
```

**Comment by JamsRepos** [comment]
Seems to be an issue with PlexAPI. A similar issue has been opened there.

https://github.com/pkkid/python-plexapi/issues/1435

**Comment by lucaspef** [comment]
I believe the invitations now go through here:
https://plex.tv/api/v2/shared_servers/invites/owned/pending?X-Plex-Client-Identifier=XXXXXXX&X-Plex-Token=XXXXXX
can be pending or accepted

**Comment by NOnooSS** [comment]
Indeed I saw that few times but how can we fix it ? Manually possible by changing configuration ?

**Comment by JamsRepos** [comment]
You cannot fix it unless the PlexAPI library is updated.

**Comment by CappiSteijns** [comment]
Just for my understanding, I just setup Wizarr and got this message. Does that mean Wizarr is temporarily not useable?

**Comment by nicholiswood** [comment]
It seems like the account creating fails, but if the user tries again it usually goes through without that error. They should receive an email to accept the server invite afterwards.

**Comment by CappiSteijns** [comment]
> It seems like the account creating fails, but if the user tries again it usually goes through without that error. They should receive an email to accept the server invite afterwards. 

Yes noticed the email where you can accept the invite, so it kind of still works.

**Comment by JamsRepos** [comment]
The last time some routes got deprecated I had to make the PR and push to get it merged. Seems like active development on the Python library isn't much a thing anymore, just a case of posting in that issue until it's done.
