### ISSUE TITLE
Internal Server error 500

### ISSUE THREAD

**Issue by GregTroar** [Wizarrrr/wizarr#47]
Keep having a lot of different error 500.
I can create my login and pass and then when I enter the information for the name, plex token and libraries as well as overseerr I click save and get an error 500

[2023-02-11 00:29:14,261] ERROR in app: Exception on /settings [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/admin.py", line 91, in preferences
    if discord_id:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'discord_id' where it is not associated with a value
ERROR:root:500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I am using it behind a reverse proxy if that changes anything ?!?

Thanks

**Comment by mtthidoteu** [comment]
Fixed with latest release
