### ISSUE TITLE
Pi image

### ISSUE THREAD

**Issue by Rocknrolldoggie** [Wizarrrr/wizarr#62]
Hi there. Any plans to make an image for use  on raspberry pi (armv7) ? Raspberry pi used by quite allot of people to host their plex servers incl me 😃

**Comment by mtthidoteu** [comment]
The image comes with an arm64, which from what I understood is supported on RPI isn't it?

**Comment by Rocknrolldoggie** [comment]
Hi Matthieu

The 64bit for pi’s is fairly new and most especially older than the pi 4
run on 32 bit. Pi 4 is also shipped on 32 bit when new.

**Comment by Rocknrolldoggie** [comment]
Hi Matthieu

Any more thoughts on the pi image ? Naturally understand if you cant do it just would like to know if its a future possible thing.

**Comment by sander1095** [comment]
Hi @mtthidoteu ! I got very excited when I learned about the existence of wizarr on Reddit. Sadly, I'm running into the same problem as @Rocknrolldoggie, the docker compose doesn't work with my raspberry pi 3b+ that is running raspbian 32bit.

When I try to build the docker image myself and run it with the following command, the application does work **mostly**.

I have to run `docker run` which results in some errors in some errors about session files not being found. After running `docker container restart` it DOES run and I can set up the application.

WHen I try to create an invitation, I get shown the login page again, and the invitations page is empty after logging in again. Not sure what is going on there :).

Also when restarting the application after trying to create an invitation,I get the following logs:

```
[2023-03-08 23:45:59 +0100] [1] [INFO] Shutting down: Master
[2023-03-08 23:46:03 +0100] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-08 23:46:03 +0100] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
[2023-03-08 23:46:03 +0100] [1] [INFO] Using worker: sync
[2023-03-08 23:46:03 +0100] [7] [INFO] Booting worker with pid: 7
[2023-03-08 23:46:03 +0100] [8] [INFO] Booting worker with pid: 8
[2023-03-08 23:46:03 +0100] [9] [INFO] Booting worker with pid: 9
WARNING:root:Exception raised while handling cache file './database/sessions/2029240f6d1128be89ddc32729463129'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cachelib/file.py", line 256, in set
    self._run_safely(os.chmod, filename, self._mode)
  File "/usr/local/lib/python3.11/site-packages/cachelib/file.py", line 324, in _run_safely
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './database/sessions/2029240f6d1128be89ddc32729463129'
WARNING:root:Exception raised while handling cache file './database/sessions/2029240f6d1128be89ddc32729463129'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cachelib/file.py", line 258, in set
    fsize = Path(filename).stat().st_size
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'database/sessions/2029240f6d1128be89ddc32729463129'
2023-03-08 23:46:06,865 - ERROR - Exception on /admin [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3236, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/admin.py", line 30, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/data/app/admin.py", line 40, in admin
    setup = Settings.get_or_none(Settings.key == "server_verified")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 6634, in get_or_none
    return cls.get(*query, **filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 6629, in get
    return sq.get()
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 7077, in get
    return clone.execute(database)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2206, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3244, in execute
    return self.execute_sql(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3236, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: settings
2023-03-08 23:46:06,896 - ERROR - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Furthermore, sometimes when I click on `Users` or `Invitations` I see the login screen.
Firefox dev tools tell me there was a 502 bad gateway error when I tried to navigate to that screen. I don't really see any logs to debug this further.

I doubt these things are related to the Pi 3b+, so I'd say that after some investigation into these issues, armv7 support could easily be enabled! 🎉

**Comment by Rocknrolldoggie** [comment]
Hi sander1095. I'm also on a 3b+ unfortunately the technical part of your message is Greek to me 😀.
