### ISSUE TITLE
500 Internal Server Error when loading Users tab

### ISSUE THREAD

**Issue by 3527861318** [Wizarrrr/wizarr#63]
Along with the issue in the title, any invitation links that I generate _appear_ to work, but at the end of it the invitee does not gain access to my Plex Server. My Plex Libraries are found fine, links generate and load fine, basically no other issues as far as I am able to tell.

Plex and Docker running the Wizarr container are on different machines on the same LAN. I have Overseerr set up fairly identically and it works entirely as intended, just for reference.

2023-02-18 19:54:34 [2023-02-18 19:54:34,840] ERROR in app: Exception on /users [GET]
2023-02-18 19:54:34 Traceback (most recent call last):
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
2023-02-18 19:54:34     response = self.full_dispatch_request()
2023-02-18 19:54:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
2023-02-18 19:54:34     rv = self.handle_user_exception(e)
2023-02-18 19:54:34          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-18 19:54:34     rv = self.dispatch_request()
2023-02-18 19:54:34          ^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-18 19:54:34     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-18 19:54:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/data/app/admin.py", line 28, in decorated_function
2023-02-18 19:54:34     return f(*args, **kwargs)
2023-02-18 19:54:34            ^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/data/app/admin.py", line 266, in users
2023-02-18 19:54:34     admin = MyPlexAccount(Settings.get(Settings.key == "plex_token").value)
2023-02-18 19:54:34             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 97, in __init__
2023-02-18 19:54:34     data, initpath = self._signin(username, password, code, timeout)
2023-02-18 19:54:34                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 107, in _signin
2023-02-18 19:54:34     data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
2023-02-18 19:54:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-18 19:54:34   File "/usr/local/lib/python3.11/site-packages/plexapi/myplex.py", line 192, in query
2023-02-18 19:54:34     raise BadRequest(message)
2023-02-18 19:54:34 plexapi.exceptions.BadRequest: (429) too_many_requests; https://plex.tv/users/sign_in.xml 
2023-02-18 19:54:34 ERROR:root:500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by joseluislucas** [comment]
Same problem here. Just upgraded to new version,

**Comment by mtthidoteu** [comment]
`plexapi.exceptions.BadRequest: (429) too_many_requests;` it means you are sending too many request to the Plex API.
A better handling of this issue is on its way, but unfortunately nothing can really be done about it. I have implemented caching for better handling of this though

**Comment by 8321876218** [comment]
I am having this exact issue as well. Does anyone know of a fix? I'm not sure "I" am sending too many requests as I'm assuming Wizarr is sending as many as is designed. Even stopping everything but Plex and Wizarr the same error occurs.

From what I can gather, error 429 is too many requests in an amount of time, not just sheer quantity of requests. Could something as dirty as adding a time.sleep() between the API calls be a work around?

**Comment by mtthidoteu** [comment]
With the next release. I’ve added a chaching function which will cache the users until a user is either invited or deleted, so it’ll only do the requests very sparingly. I’ll also add a proper error message if somehow the requests are reached!On 20 Feb 2023, at 19:55, 8321876218 ***@***.***> wrote:﻿
I am having this exact issue as well. Does anyone know of a fix? I'm not sure "I" am sending too many requests as I'm assuming Wizarr is sending as many as is designed. Even stopping everything but Plex and Wizarr the same error occurs.
From what I can gather, error 429 is too many requests in an amount of time, not just sheer quantity of requests. Could something as dirty as adding a time.sleep() between the API calls be a work around?

**Comment by 3527861318** [comment]
You rock mtthidoteu! 1.6.4 finally resolved this issue for me!
