### ISSUE TITLE
[BUG] 1.6.3 (docker) fails to start due to logging exception: ValueError: Unknown level: 'info'

### ISSUE THREAD

**Issue by tikibozo** [Wizarrrr/wizarr#72]
**Describe the bug**
Startup error after pulling 1.6.3 and booting the container. Reverting to 1.6.2 works fine. (I have a nightly script that does a docker-compose -up to refresh versions)

**Logs**
```
wizarr               | [2023-02-22 08:16:37 -0800] [1] [INFO] Starting gunicorn 20.1.0
wizarr               | [2023-02-22 08:16:37 -0800] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
wizarr               | [2023-02-22 08:16:37 -0800] [1] [INFO] Using worker: sync
wizarr               | [2023-02-22 08:16:37 -0800] [7] [INFO] Booting worker with pid: 7
wizarr               | [2023-02-22 08:16:37 -0800] [8] [INFO] Booting worker with pid: 8
wizarr               | [2023-02-22 08:16:37 -0800] [9] [INFO] Booting worker with pid: 9
wizarr               | [2023-02-22 08:16:37 -0800] [7] [ERROR] Exception in worker process
wizarr               | Traceback (most recent call last):
wizarr               |   File "/usr/local/lib/python3.11/logging/config.py", line 616, in configure
wizarr               |     self.configure_logger(name, loggers[name])
wizarr               |   File "/usr/local/lib/python3.11/logging/config.py", line 797, in configure_logger
wizarr               |     self.common_logger_config(logger, config, incremental)
wizarr               |   File "/usr/local/lib/python3.11/logging/config.py", line 782, in common_logger_config
wizarr               |     logger.setLevel(logging._checkLevel(level))
wizarr               |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr               |   File "/usr/local/lib/python3.11/logging/__init__.py", line 207, in _checkLevel
wizarr               |     raise ValueError("Unknown level: %r" % level)
wizarr               | ValueError: Unknown level: 'info'
wizarr               |
wizarr               | The above exception was the direct cause of the following exception:
wizarr               |
wizarr               | Traceback (most recent call last):
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
wizarr               |     worker.init_process()
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
wizarr               |     self.load_wsgi()
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
wizarr               |     self.wsgi = self.app.wsgi()
wizarr               |                 ^^^^^^^^^^^^^^^
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
wizarr               |     self.callable = self.load()
wizarr               |                     ^^^^^^^^^^^
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
wizarr               |     return self.load_wsgiapp()
wizarr               |            ^^^^^^^^^^^^^^^^^^^
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
wizarr               |     return util.import_app(self.app_uri)
wizarr               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr               |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
wizarr               |     mod = importlib.import_module(module)
wizarr               |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr               |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
wizarr               |     return _bootstrap._gcd_import(name[level:], package, level)
wizarr               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wizarr               |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
wizarr               |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
wizarr               |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
wizarr               |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
wizarr               |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
wizarr               |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
wizarr               |   File "/data/run.py", line 1, in <module>
wizarr               |     from app import app
wizarr               |   File "/data/app/__init__.py", line 60, in <module>
wizarr               |     logging.config.dictConfig(LOGGING_CONFIG)
wizarr               |   File "/usr/local/lib/python3.11/logging/config.py", line 812, in dictConfig
wizarr               |     dictConfigClass(config).configure()
wizarr               |   File "/usr/local/lib/python3.11/logging/config.py", line 618, in configure
wizarr               |     raise ValueError('Unable to configure logger '
wizarr               | ValueError: Unable to configure logger ''
wizarr               | [2023-02-22 08:16:37 -0800] [7] [INFO] Worker exiting (pid: 7)
```
[other two workers fail the same way, gunicorn halts the server, and the container exits]

**Comment by mtthidoteu** [comment]
`ValueError: Unknown level: 'info'`
Have you set LOG_LEVEL=info? Try LOG_LEVEL=INFO.
I'll make it uppercase from now on so that doesn't happen

**Comment by tikibozo** [comment]
Oh interesting - I did, unintentionally. For my compose setup I pulled all my environment variables into a seperate file, which had a side effect of all the variables being imported to all the containers. So yes -- there's another container which also uses LOG_LEVEL, and it was set to "info" for that container. Interesting that it only affected wizarr as of 1.6.3, but that's totally my fault, thanks. I've been meaning to untangle that and I'll do so now.

**Comment by mtthidoteu** [comment]
> Oh interesting - I did, unintentionally. For my compose setup I pulled all my environment variables into a seperate file, which had a side effect of all the variables being imported to all the containers. So yes -- there's another container which also uses LOG_LEVEL, and it was set to "info" for that container. Interesting that it only affected wizarr as of 1.6.3, but that's totally my fault, thanks. I've been meaning to untangle that and I'll do so now.

I've put something to stop it from completely crashing the whole program, from now on if the value isn't right, it'll just ignore it! 

And yes it's been like that since 1.6.3 as I've changed the way the logging works :)

**Comment by tikibozo** [comment]
Great fix 😅 Sorry for the trouble.
