### ISSUE TITLE
[BUG] HTTP Status 500 after accepting invite

### ISSUE THREAD

**Issue by strenkml** [Wizarrrr/wizarr#87]
**Describe the bug**
I have my config set to use Plex, when a user accepts an invite Wizarr tries to import the user into my Ombi but is using the Jellyfin url.

**Screenshots**
![Settings](https://i.imgur.com/OTdjPpw.png)

**Logs**
If applicable, add logs to help explain your problem
```
2023-02-28 10:32:59,273 - ERROR - Exception on /setup [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/web.py", line 65, in setup
    ombi_RunAllUserImporters()
  File "/data/app/ombi.py", line 28, in ombi_RunAllUserImporters
    return ombi_RunUserImporter('jellyfin')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/ombi.py", line 19, in ombi_RunUserImporter
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'Ombi/api/v1/Job/jellyfinUserImporter/': No scheme supplied. Perhaps you meant https://Ombi/api/v1/Job/jellyfinUserImporter/?
2023-02-28 10:32:59,279 - ERROR - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by strenkml** [comment]
The error in the log was resolved by adding the correct url in the Request Instance field.  Though the user did not import and I am guessing it is because it is still using the Jellyfin endpoint.
